joke_task:
  description: >
    Create a list of 10 jokes
  expected_output: >
    A list with 10 bullet points of jokes
  agent: joke_creator

add_emojis_task:
  description: >
    Add emojis to the jokes
  expected_output: >
    A list of 10 bullet points of jokes with emojis
    Formatted as markdown without '```'
  agent: add_emojis
